import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import ProductComponent from "../components/Product";
import { baseUrl } from "../config";
import { Product } from "../types/Product";
import { Main } from "./styles";

type HomeProps = { products: Product[] };

const Home: NextPage<HomeProps> = ({ products }) => {
  return (
    <div className="container">
      <Head>
        <title>Products</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        {products.map((product) => (
          <ProductComponent key={product.id} product={product} />
        ))}
      </Main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  const response = await fetch(baseUrl + "/products");
  const data = await response.json();

  return {
    props: {
      products: data,
    },
    revalidate: 10,
  };
};

export default Home;
